# Generated by Django 2.2.1 on 2020-04-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_name', models.CharField(max_length=60)),
                ('mountain_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='texts_on_website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_text_is', models.CharField(max_length=500)),
                ('text_on_website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='peaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('gps', models.CharField(max_length=80)),
                ('quick_description', models.CharField(max_length=94)),
                ('text', models.TextField()),
                ('name_of_mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nature.mountain')),
            ],
        ),
    ]
