# Generated by Django 2.2.1 on 2020-04-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='mountain_image',
        ),
    ]
